### ISSUE TITLE
2.1 Geolocation

### ISSUE THREAD

**Issue by KrijnHoetmer** [DaveBitter/minor-webdev_browser-technologies#15]
> In order to still get peoples latitude and longitude two inputs are shown when on those browsers.

Not really, I don't get [to see anything](http://webdev.davebitter.com/exercises/bt/week_2/index_4.html) :) Do you? (Hint: geolocation doesn't work over http anymore, you need https. So your feature detect works (the browser does support the API), but the feature itself doesn't. What's a better way to do this?

**Comment by DaveBitter** [comment]
Ah, I didn't know that. Well, I could make this part of the check by doing something like ```location.protocol != 'https:'```
